spring:
  datasource:
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties=druid.stat.mergeSql: true;druid.stat.slowSqlMillis=5000
      one:
        url: jdbc:mysql://localhost:3306/third_pay?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
      two:
        url: jdbc:mysql://localhost:3306/second_pay?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
      three:
        url: jdbc:mysql://localhost:3306/first_pay?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
  jta:
        enabled: true
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
        max-actives: 200
        enable-logging: false
  jpa:
    database: MySQL
    properties:
            hibernate:
              show_sql: true
              format_sql: true
    #hibernate:
      #ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
logging:
  level: info
server:
  port: 8443
  context-path: /
  ssl:
    key-store: classpath:.keystore
    key-password: 123456
    key-store-type: JKS
    key-alias: tomcat
